x-common:
  &common
  image: apache/airflow:2.8.3
  user: "${AIRFLOW_UID:-50000}:0"
  env_file: 
    - .env
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./data:/opt/airflow/data
    - ./models:/opt/airflow/models
    - /var/run/docker.sock:/var/run/docker.sock
  networks:
    - default

x-depends-on:
  &depends-on
  depends_on:
    postgres:
      condition: service_healthy
    airflow-init:
      condition: service_completed_successfully

services:
  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    env_file:
      - .env
    networks:
      - default

  scheduler:
    <<: [*common, *depends-on]
    # <<: *depends-on
    container_name: airflow-scheduler
    command: scheduler
    restart: on-failure
    ports:
      - "8793:8793"

  webserver:
    <<: [*common, *depends-on]
    # <<: *depends-on
    container_name: airflow-webserver
    restart: always
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 30s
      retries: 5
  
  airflow-init:
    <<: *common
    container_name: airflow-init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        mkdir -p /opt/logs /opt/dags /opt/plugins
        chown -R "${AIRFLOW_UID}:0" /opt/{logs,dags,plugins}
        exec /entrypoint airflow version


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    container_name: elasticsearch
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      # - xpack.reporting.capture.browser.chromium.disableSandbox=False
      # - xpack.reporting.enabled=False
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 #atur memori 65536
        hard: 65536 #atur memori 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - default
      
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.13.0
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - default

volumes:
  postgres-data:
  elasticsearch-data:

networks:
  default:
    driver: bridge

